### ISSUE TITLE
ceph2fs do not work

### ISSUE THREAD

**Issue by hnuzhoulin** [hu-berlin-cms/seafile-ceph-tools#2]
ceph df:
    commits                13     10710      0         20
    fs                     14     14949      0         66
    blocks                 15     26465k     0.03      31
first I download seafobj,then I run:

```
./seafile-ceph2fs   --client admin --blocks-pool blocks --commits-pool commits --fs-pool fs  /tmp/testzl/ -V 
```

But I got nothing,using pdb to track it.  **ioctx.list_objects()** return empty.

BTW,how can I get the right namespace?

**Comment by egroeper** [comment]
Which version of ceph are you using?
I didn't write it, but for this to work you need a fairly recent ceph release.
You need at least ceph 0.88 (see http://tracker.ceph.com/issues/9031), which means you need Ceph Hammer (0.94) in stable releases.

Without Hammer, you will need an external source (seafile database) to get the namespaces. And of course you then would need to adapt my script.

I will update the README

**Comment by hnuzhoulin** [comment]
Thanks so much.
my ceph version is Firefly.I will  adapt your script.

**Comment by hnuzhoulin** [comment]
BTW,that I want  to do is migrate fs to ceph.
I lack inspiration until I look your script.   ^_^
